# Generated by Django 5.1.4 on 2024-12-05 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_alter_checker_id_alter_house_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='image',
            field=models.CharField(max_length=350),
        ),
    ]
